DELETE FROM GENRE;
DELETE FROM RATING;
DELETE FROM STATUS;
DELETE FROM USERS;
DELETE FROM FILMS;
DELETE FROM FILM_GENRE;
DELETE FROM FILM_LIKES;
DELETE FROM FRIENDSHIP;
INSERT INTO genre (id, genre_name) VALUES (1, 'Комедия');
INSERT INTO genre (id, genre_name) VALUES (2, 'Драма');
INSERT INTO genre (id, genre_name) VALUES (3, 'Мультфильм');
INSERT INTO genre (id, genre_name) VALUES (4, 'Триллер');
INSERT INTO genre (id, genre_name) VALUES (5, 'Документальный');
INSERT INTO genre (id, genre_name) VALUES (6, 'Боевик');
INSERT INTO rating (id, name) VALUES(1, 'G');
INSERT INTO rating (id, name) VALUES(2, 'PG');
INSERT INTO rating (id, name) VALUES(3, 'PG-13');
INSERT INTO rating (id, name) VALUES(4, 'R');
INSERT INTO rating (id, name) VALUES(5, 'NC-17');
INSERT INTO status (id, description) VALUES (1, 'confirmed');
INSERT INTO status (id, description) VALUES (2, 'not confirmed');