CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200),
    description varchar,
    release_date date,
    duration varchar,
    rating varchar
);
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar,
    login varchar,
    name varchar,
    birth_date date
);
CREATE TABLE IF NOT EXISTS film_genre (
    film_id varchar,
    genre_id varchar
);
CREATE TABLE IF NOT EXISTS genres (
    genre_id varchar,
    genre_name varchar
);
CREATE TABLE IF NOT EXISTS film_likes (
    film_id varchar,
    user_id varchar
);
CREATE TABLE IF NOT EXISTS friendship (
    user_id varchar,
    friend_id varchar,
    friendship_status varchar
);